/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.User;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author X1
 */
public class Admin_View extends javax.swing.JFrame {
    Color DefaultColor, ClickedColor;

    public Admin_View(User u){
        initComponents();
        setLocationRelativeTo(null);
        DefaultColor = new Color(13, 36, 51);
        ClickedColor = new Color(170,117,10);
        dashBoard();
        
        lbl_UserID.setText(u.getUserName());
//        lbl_UserRole.setText(u.getRole());
       
        menuName.setText("| Trang Chủ");
        
//        QuanLyBanHang banHang = new QuanLyBanHang();
//        jGUIForms.removeAll();
//        jGUIForms.add(banHang).setVisible(true);
//
//        QuanLySanPham sanPham = new QuanLySanPham();
//        jGUIForms.removeAll();
//        jGUIForms.add(sanPham).setVisible(true);


        TrangChu trangChu = new TrangChu();
        jGUIForms.removeAll();
        jGUIForms.add(trangChu).setVisible(true);

//          Admin_Window a_W = new Admin_Window();
//          jGUIForms.removeAll();
//          jGUIForms.add(a_W).setVisible(true);
    }

    
    void dashBoard(){
        trangChu.setBackground(DefaultColor);
        banHang.setBackground(DefaultColor);
        sanPham.setBackground(DefaultColor);
        nhanSu.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        taiKhoan.setBackground(DefaultColor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        verticalLayout = new javax.swing.JPanel();
        menuName = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        lbl_UserID = new javax.swing.JLabel();
        txtUser_ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        horizontalMenu = new javax.swing.JPanel();
        trangChu = new javax.swing.JPanel();
        lblTrangChu = new javax.swing.JLabel();
        banHang = new javax.swing.JPanel();
        lblBanHang = new javax.swing.JLabel();
        sanPham = new javax.swing.JPanel();
        lblSanPham = new javax.swing.JLabel();
        nhanSu = new javax.swing.JPanel();
        lblNhanSu = new javax.swing.JLabel();
        khachHang = new javax.swing.JPanel();
        lblKhachHang = new javax.swing.JLabel();
        taiKhoan = new javax.swing.JPanel();
        lblTaiKhoan = new javax.swing.JLabel();
        exit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        jGUIForms = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 690));

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verticalLayout.setBackground(new java.awt.Color(220, 117, 28));
        verticalLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuName.setFont(new java.awt.Font("Montserrat", 3, 12)); // NOI18N
        menuName.setForeground(new java.awt.Color(255, 255, 255));
        menuName.setText("mono");
        verticalLayout.add(menuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 30));

        logo.setFont(new java.awt.Font("Montserrat ExtraBold", 3, 20)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-polo.png"))); // NOI18N
        logo.setText("PolyPolo");
        verticalLayout.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 50));

        lbl_UserID.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        lbl_UserID.setText("stallion");
        verticalLayout.add(lbl_UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 60, 20));

        txtUser_ID.setBackground(new java.awt.Color(224, 224, 224));
        txtUser_ID.setEnabled(false);
        verticalLayout.add(txtUser_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 110, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-icon20.png"))); // NOI18N
        verticalLayout.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 40, 40));

        bg.add(verticalLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 80));

        horizontalMenu.setBackground(new java.awt.Color(13, 36, 51));
        horizontalMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trangChu.setBackground(new java.awt.Color(13, 36, 51));
        trangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangChuMouseClicked(evt);
            }
        });

        lblTrangChu.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setText("Trang Chủ");

        javax.swing.GroupLayout trangChuLayout = new javax.swing.GroupLayout(trangChu);
        trangChu.setLayout(trangChuLayout);
        trangChuLayout.setHorizontalGroup(
            trangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTrangChu)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        trangChuLayout.setVerticalGroup(
            trangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trangChuLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lblTrangChu)
                .addContainerGap())
        );

        horizontalMenu.add(trangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 30));

        banHang.setBackground(new java.awt.Color(13, 36, 51));
        banHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banHangMouseClicked(evt);
            }
        });

        lblBanHang.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblBanHang.setForeground(new java.awt.Color(255, 255, 255));
        lblBanHang.setText("Bán Hàng");

        javax.swing.GroupLayout banHangLayout = new javax.swing.GroupLayout(banHang);
        banHang.setLayout(banHangLayout);
        banHangLayout.setHorizontalGroup(
            banHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(banHangLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblBanHang)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        banHangLayout.setVerticalGroup(
            banHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(banHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBanHang)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        horizontalMenu.add(banHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 30));

        sanPham.setBackground(new java.awt.Color(13, 36, 51));
        sanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sanPhamMouseClicked(evt);
            }
        });

        lblSanPham.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblSanPham.setForeground(new java.awt.Color(255, 255, 255));
        lblSanPham.setText("Sản Phẩm");

        javax.swing.GroupLayout sanPhamLayout = new javax.swing.GroupLayout(sanPham);
        sanPham.setLayout(sanPhamLayout);
        sanPhamLayout.setHorizontalGroup(
            sanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanPhamLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblSanPham)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        sanPhamLayout.setVerticalGroup(
            sanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSanPham)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        horizontalMenu.add(sanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, -1));

        nhanSu.setBackground(new java.awt.Color(13, 36, 51));
        nhanSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanSuMouseClicked(evt);
            }
        });

        lblNhanSu.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblNhanSu.setForeground(new java.awt.Color(255, 255, 255));
        lblNhanSu.setText("Nhân Sự");

        javax.swing.GroupLayout nhanSuLayout = new javax.swing.GroupLayout(nhanSu);
        nhanSu.setLayout(nhanSuLayout);
        nhanSuLayout.setHorizontalGroup(
            nhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanSuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblNhanSu)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        nhanSuLayout.setVerticalGroup(
            nhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanSuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNhanSu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        horizontalMenu.add(nhanSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, -1));

        khachHang.setBackground(new java.awt.Color(13, 36, 51));
        khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHangMouseClicked(evt);
            }
        });

        lblKhachHang.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        lblKhachHang.setText("Khách Hàng");

        javax.swing.GroupLayout khachHangLayout = new javax.swing.GroupLayout(khachHang);
        khachHang.setLayout(khachHangLayout);
        khachHangLayout.setHorizontalGroup(
            khachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblKhachHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        khachHangLayout.setVerticalGroup(
            khachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKhachHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        horizontalMenu.add(khachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, -1));

        taiKhoan.setBackground(new java.awt.Color(13, 36, 51));
        taiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taiKhoanMouseClicked(evt);
            }
        });

        lblTaiKhoan.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lblTaiKhoan.setText("Tài Khoản");

        javax.swing.GroupLayout taiKhoanLayout = new javax.swing.GroupLayout(taiKhoan);
        taiKhoan.setLayout(taiKhoanLayout);
        taiKhoanLayout.setHorizontalGroup(
            taiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taiKhoanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTaiKhoan)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        taiKhoanLayout.setVerticalGroup(
            taiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTaiKhoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        horizontalMenu.add(taiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 120, -1));

        exit.setBackground(new java.awt.Color(13, 36, 51));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("Exit");

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblExit)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        horizontalMenu.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 120, -1));

        bg.add(horizontalMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 620));

        jGUIForms.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jGUIFormsLayout = new javax.swing.GroupLayout(jGUIForms);
        jGUIForms.setLayout(jGUIFormsLayout);
        jGUIFormsLayout.setHorizontalGroup(
            jGUIFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jGUIFormsLayout.setVerticalGroup(
            jGUIFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        bg.add(jGUIForms, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 980, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void trangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangChuMouseClicked
        // TODO add your handling code here:
    //    side1.setBackground(Color.ORANGE);
        trangChu.setBackground(ClickedColor);
        banHang.setBackground(DefaultColor);
        sanPham.setBackground(DefaultColor);
        nhanSu.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        taiKhoan.setBackground(DefaultColor);
        
        menuName.setText("| Trang Chủ");
        TrangChu trangChu = new TrangChu();
        jGUIForms.removeAll();
        jGUIForms.add(trangChu).setVisible(true);
        
    }//GEN-LAST:event_trangChuMouseClicked

    private void banHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banHangMouseClicked
        // TODO add your handling code here:
        trangChu.setBackground(DefaultColor);
        banHang.setBackground(ClickedColor);
        sanPham.setBackground(DefaultColor);
        nhanSu.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        taiKhoan.setBackground(DefaultColor);
        
        menuName.setText("| Bán Hàng");
        
        QuanLyBanHang banHang = new QuanLyBanHang();
        jGUIForms.removeAll();
        jGUIForms.add(banHang).setVisible(true);
    }//GEN-LAST:event_banHangMouseClicked

    private void sanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanPhamMouseClicked
        // TODO add your handling code here:
        trangChu.setBackground(DefaultColor);
        banHang.setBackground(DefaultColor);
        sanPham.setBackground(ClickedColor);
        nhanSu.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        taiKhoan.setBackground(DefaultColor);
        
        menuName.setText("| Sản Phẩm");
        
        QuanLySanPham sanPham = new QuanLySanPham();
        jGUIForms.removeAll();
        jGUIForms.add(sanPham).setVisible(true);
    }//GEN-LAST:event_sanPhamMouseClicked

    private void nhanSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanSuMouseClicked
        // TODO add your handling code here:
        trangChu.setBackground(DefaultColor);
        banHang.setBackground(DefaultColor);
        sanPham.setBackground(DefaultColor);
        nhanSu.setBackground(ClickedColor);
        khachHang.setBackground(DefaultColor);
        taiKhoan.setBackground(DefaultColor);
        
        menuName.setText("| Nhân Sự");
        
        QuanLyNhanSu ns = new QuanLyNhanSu();
        jGUIForms.removeAll();
        jGUIForms.add(ns).setVisible(true);
    }//GEN-LAST:event_nhanSuMouseClicked

    private void khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHangMouseClicked
        // TODO add your handling code here:
        trangChu.setBackground(DefaultColor);
        banHang.setBackground(DefaultColor);
        sanPham.setBackground(DefaultColor);
        nhanSu.setBackground(DefaultColor);
        khachHang.setBackground(ClickedColor);
        taiKhoan.setBackground(DefaultColor);
        
        menuName.setText("| Khách Hàng");

        QuanLyKhachHang khachHang = new QuanLyKhachHang();
        jGUIForms.removeAll();
        jGUIForms.add(khachHang).setVisible(true);
    }//GEN-LAST:event_khachHangMouseClicked

    private void taiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taiKhoanMouseClicked
        // TODO add your handling code here:
        trangChu.setBackground(DefaultColor);
        banHang.setBackground(DefaultColor);
        sanPham.setBackground(DefaultColor);
        nhanSu.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        taiKhoan.setBackground(ClickedColor);
        
        menuName.setText("| Tài Khoản");

        QuanLyTaiKhoan taiKhoan = new QuanLyTaiKhoan();
        jGUIForms.removeAll();
        jGUIForms.add(taiKhoan).setVisible(true);
    }//GEN-LAST:event_taiKhoanMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        trangChu.setBackground(DefaultColor);
        banHang.setBackground(DefaultColor);
        sanPham.setBackground(DefaultColor);
        nhanSu.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        taiKhoan.setBackground(DefaultColor);
        
        JOptionPane.showMessageDialog(this, "Thanks for using our programm!!~");
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatMacLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Admin_View().setVisible(true);
                User user = new User();
                user.setUserName("junggo");
                user.setRole("vjp");

                new Admin_View(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banHang;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel horizontalMenu;
    private javax.swing.JDesktopPane jGUIForms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel khachHang;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblNhanSu;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JLabel lbl_UserID;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menuName;
    private javax.swing.JPanel nhanSu;
    private javax.swing.JPanel sanPham;
    private javax.swing.JPanel taiKhoan;
    private javax.swing.JPanel trangChu;
    private javax.swing.JTextField txtUser_ID;
    private javax.swing.JPanel verticalLayout;
    // End of variables declaration//GEN-END:variables
}
